const { test, expect } = require('@playwright/test');

// Simple visual tests for debt-strategy-complete.html
// Tests match the actual HTML structure generated by debt-strategy-visualizer

test('Debt strategy page loads and displays key sections', async ({ page }) => {
    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for data to load by checking for a data-metric element to have real data
    await page.waitForFunction(() => {
        const element = document.querySelector('[data-metric="total-debt"]');
        return element && element.textContent !== 'Loading...';
    }, { timeout: 10000 });

    // Take full page screenshot
    await page.screenshot({
        path: 'test-results/debt-strategy-full-page.png',
        fullPage: true
    });

    // Verify main sections exist
    await expect(page.locator('.stats-grid')).toBeVisible();
    await expect(page.locator('#strategy-box')).toBeVisible();
    await expect(page.locator('#debt-sequence-table')).toBeVisible();
    await expect(page.locator('#milestones-timeline')).toBeVisible();
    await expect(page.locator('#next-actions-list')).toBeVisible();
    await expect(page.locator('#acceleration-table')).toBeVisible();

    console.log('✅ All main sections are visible');
});

test('Stats grid displays four key metrics', async ({ page }) => {
    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for data to load
    await page.waitForFunction(() => {
        const element = document.querySelector('[data-metric="total-debt"]');
        return element && element.textContent !== 'Loading...';
    }, { timeout: 10000 });

    // Screenshot stats section
    await page.locator('.stats-grid').screenshot({
        path: 'test-results/stats-grid.png'
    });

    // Verify 4 stat cards exist
    const statCards = page.locator('.stat-card');
    await expect(statCards).toHaveCount(4);

    // Verify each metric has loaded (not showing "Loading...")
    await expect(page.locator('[data-metric="total-debt"]')).not.toHaveText('Loading...');
    await expect(page.locator('[data-metric="monthly-payments"]')).not.toHaveText('Loading...');
    await expect(page.locator('[data-metric="monthly-interest"]')).not.toHaveText('Loading...');
    await expect(page.locator('[data-metric="debt-free-date"]')).not.toHaveText('Loading...');

    console.log('✅ Stats grid displays all 4 metrics');
});

test('Strategy section displays recommendation', async ({ page }) => {
    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for data to load
    await page.waitForFunction(() => {
        const element = document.querySelector('[data-metric="strategy-name"]');
        return element && element.textContent !== 'Loading...';
    }, { timeout: 10000 });

    // Screenshot strategy section
    await page.locator('#strategy-box').screenshot({
        path: 'test-results/strategy-box.png'
    });

    // Verify strategy data loaded
    await expect(page.locator('[data-metric="strategy-name"]')).not.toHaveText('Loading...');
    await expect(page.locator('[data-metric="strategy-description"]')).not.toHaveText('Loading...');
    await expect(page.locator('[data-metric="strategy-reasoning"]')).not.toHaveText('Loading...');

    console.log('✅ Strategy section loaded');
});

test('Debt sequence table has rows', async ({ page }) => {
    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for table to load
    await page.waitForFunction(() => {
        const tbody = document.querySelector('#debt-sequence-body');
        const firstCell = tbody?.querySelector('td');
        return firstCell && !firstCell.textContent.includes('Loading');
    }, { timeout: 10000 });

    // Screenshot table
    await page.locator('#debt-sequence-table').screenshot({
        path: 'test-results/debt-sequence-table.png'
    });

    // Verify table has header and rows
    const headerCells = page.locator('#debt-sequence-table thead th');
    await expect(headerCells).toHaveCount(6);

    const bodyRows = page.locator('#debt-sequence-body tr');
    const rowCount = await bodyRows.count();
    expect(rowCount).toBeGreaterThan(0);

    console.log(`✅ Debt sequence table has ${rowCount} rows`);
});

test('Milestones timeline renders', async ({ page }) => {
    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for milestones to load
    await page.waitForFunction(() => {
        const timeline = document.querySelector('#milestones-timeline');
        const content = timeline?.textContent || '';
        return !content.includes('Loading milestones');
    }, { timeout: 10000 });

    // Screenshot milestones
    await page.locator('#milestones-timeline').screenshot({
        path: 'test-results/milestones-timeline.png'
    });

    // Verify timeline exists and has content
    await expect(page.locator('#milestones-timeline')).toBeVisible();
    const milestoneItems = page.locator('#milestones-timeline .timeline-item');
    const count = await milestoneItems.count();
    expect(count).toBeGreaterThan(0);

    console.log(`✅ Milestones timeline has ${count} items`);
});

test('Next actions list populates', async ({ page }) => {
    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for actions to load
    await page.waitForFunction(() => {
        const list = document.querySelector('#next-actions-list');
        const content = list?.textContent || '';
        return !content.includes('Loading actions');
    }, { timeout: 10000 });

    // Screenshot actions section
    await page.locator('.section:has(#next-actions-list)').screenshot({
        path: 'test-results/next-actions.png'
    });

    // Verify list has items
    const actionItems = page.locator('#next-actions-list .action-item');
    const count = await actionItems.count();
    expect(count).toBeGreaterThan(0);

    console.log(`✅ Next actions list has ${count} items`);
});

test('Acceleration scenarios table loads', async ({ page }) => {
    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for table to load
    await page.waitForFunction(() => {
        const tbody = document.querySelector('#acceleration-body');
        const firstCell = tbody?.querySelector('td');
        return firstCell && !firstCell.textContent.includes('Loading');
    }, { timeout: 10000 });

    // Screenshot table
    await page.locator('#acceleration-table').screenshot({
        path: 'test-results/acceleration-scenarios.png'
    });

    // Verify table has rows
    const bodyRows = page.locator('#acceleration-body tr');
    const rowCount = await bodyRows.count();
    expect(rowCount).toBeGreaterThan(0);

    console.log(`✅ Acceleration table has ${rowCount} scenarios`);
});

test('Conditional mortgage section', async ({ page }) => {
    const fs = require('fs');
    const path = require('path');

    // Load inventory to check if mortgages exist
    const inventoryPath = path.join(__dirname, '..', 'debt-inventory-current.json');
    const inventory = JSON.parse(fs.readFileSync(inventoryPath, 'utf-8'));

    const hasMortgages = inventory.debts.some(d => d.accountType === 'mortgage');

    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for page to load
    await page.waitForFunction(() => {
        const element = document.querySelector('[data-metric="total-debt"]');
        return element && element.textContent !== 'Loading...';
    }, { timeout: 10000 });

    const mortgageSection = page.locator('#mortgage-section');

    if (hasMortgages) {
        // Should be visible and have content
        const content = await mortgageSection.textContent();
        expect(content.trim().length).toBeGreaterThan(0);
        console.log('✅ Mortgage section rendered (mortgages exist)');

        await mortgageSection.screenshot({
            path: 'test-results/mortgage-section.png'
        });
    } else {
        // Should be empty
        const content = await mortgageSection.textContent();
        expect(content.trim().length).toBe(0);
        console.log('✅ Mortgage section empty (no mortgages)');
    }
});

test('Conditional promotional alert section', async ({ page }) => {
    const fs = require('fs');
    const path = require('path');

    // Load inventory to check if promo debts exist
    const inventoryPath = path.join(__dirname, '..', 'debt-inventory-current.json');
    const inventory = JSON.parse(fs.readFileSync(inventoryPath, 'utf-8'));

    const hasPromos = inventory.debts.some(d => d.promotionalAPR);

    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for page to load
    await page.waitForFunction(() => {
        const element = document.querySelector('[data-metric="total-debt"]');
        return element && element.textContent !== 'Loading...';
    }, { timeout: 10000 });

    const promoSection = page.locator('#promo-alert-section');

    if (hasPromos) {
        // Should be visible and have content
        const content = await promoSection.textContent();
        expect(content.trim().length).toBeGreaterThan(0);
        console.log('✅ Promotional alert rendered (promo debts exist)');

        await promoSection.screenshot({
            path: 'test-results/promo-alert.png'
        });
    } else {
        // Should be empty
        const content = await promoSection.textContent();
        expect(content.trim().length).toBe(0);
        console.log('✅ Promotional alert empty (no promo debts)');
    }
});

test('Visual regression - full page baseline', async ({ page }) => {
    await page.goto('http://localhost:8000/debt-strategy-complete.html');

    // Wait for all content to load
    await page.waitForFunction(() => {
        const totalDebt = document.querySelector('[data-metric="total-debt"]');
        const strategyName = document.querySelector('[data-metric="strategy-name"]');
        const debtTable = document.querySelector('#debt-sequence-body');

        return totalDebt && totalDebt.textContent !== 'Loading...' &&
               strategyName && strategyName.textContent !== 'Loading...' &&
               debtTable && !debtTable.textContent.includes('Loading');
    }, { timeout: 15000 });

    // Additional wait for any animations/transitions
    await page.waitForTimeout(2000);

    // Take baseline screenshot
    await page.screenshot({
        path: 'test-results/debt-strategy-baseline.png',
        fullPage: true
    });

    console.log('✅ Visual regression baseline captured');
});
